spring:
  application:
    name: contact-activity-service
  security:
    basic:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://db.rdczmzmusjfemlynaqdf.supabase.co:5432/postgres
    username: postgres
    password: Icecoldkilla@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    placeholder-replacement: false
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${SUPABASE_DATABASE_URL}
    schemas: contact_activity
  redis:
    host: localhost
    port: 6379
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
    discovery:
      enabled: true
      service-id: ${spring.application.name}
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
      open-in-view: false

# Contact Core Service Integration
contact:
  core:
    service:
      url: http://contact-core-service/api/v1
      timeout: 5000
      retry:
        max-attempts: 3
        initial-interval: 1000
        multiplier: 2
        max-interval: 5000
      circuit-breaker:
        enabled: true
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-size: 10

server:
  port: 8082
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: db

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    com.salesflow: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.springframework.security: DEBUG
    com.salesflow.activity.client.ContactCoreClient: DEBUG
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

# Eureka Client Configuration
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10 