spring:
  datasource:
    url: ${SUPABASE_DATABASE_URL:jdbc:postgresql://db.rdczmzmusjfemlynaqdf.supabase.co:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Icecoldkilla@123}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-test-query: SELECT 1
      socket-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        connection:
          timeout: 60000
    show-sql: true
  flyway:
    enabled: false
  sql:
    init:
      mode: never

server:
  port: 8081
  servlet:
    context-path: /api

eureka:
  client:
    enabled: false

jwt:
  secret-key: test-secret-key-for-unit-tests-not-for-production-use
  access-token-validity-in-minutes: 30
  refresh-token-validity-in-days: 7

logging:
  level:
    com.salesflow.auth: DEBUG
    org.springframework.security: INFO 