spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/salesflowdb-dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false  # Disable Spring Boot auto-configuration for Flyway
    repair-on-start: true  # This will be used by our custom FlywayConfig
    validate-on-migrate: false  # Skip validation
    # The locations below are not used by Spring Boot's auto-configuration (since enabled=false)
    # But they document the locations that are hardcoded in FlywayConfig.java
    locations:
      - classpath:db/migration/public  # Used by FlywayConfig for public schema
      - classpath:db/migration/auth    # Used by FlywayConfig for auth schema
      - classpath:db/migration/tenant  # Used by FlywayConfig for tenant schemas
    schemas:
      - public
      - auth
    create-schemas: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:test@example.com}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

server:
  port: 8081
  servlet:
    context-path: /

eureka:
  client:
    enabled: false  # Disable Eureka client for now
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret-key: ${JWT_SECRET_KEY:thisIsAVerySecureKeyForJwtTokenSigningThatShouldBeReplaced}
  access-token-validity-in-minutes: ${ACCESS_TOKEN_VALIDITY:30}
  refresh-token-validity-in-days: ${REFRESH_TOKEN_VALIDITY:7}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}
  whatsapp-number: ${TWILIO_WHATSAPP_NUMBER}

app:
  otp:
    length: ${OTP_LENGTH:6}
    expiry-minutes: ${OTP_EXPIRY_MINUTES:5}

logging:
  level:
    com.salesflow.auth: ${LOGGING_LEVEL_COM_SALESFLOW_AUTH:DEBUG}
    com.salesflow.auth.tenant: ${LOGGING_LEVEL_TENANT:DEBUG}
    com.salesflow.auth.filter: ${LOGGING_LEVEL_TENANT:DEBUG}
    org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: ${LOGGING_LEVEL_FLYWAY:INFO}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

tenant:
  baseDomain: ${TENANT_BASE_DOMAIN:salesflow.com}
  localDevelopmentMode: ${TENANT_LOCAL_MODE:true}
  localPort: ${TENANT_LOCAL_PORT:8081}
  enableHeaderResolution: true
  tenantHeader: ${TENANT_HEADER:X-Tenant-ID}
  defaultTenant: ${DEFAULT_TENANT:acmecorp}

