spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  sql:
    init:
      mode: never

server:
  port: 8081
  servlet:
    context-path: /api

eureka:
  client:
    enabled: false

jwt:
  secret-key: test-secret-key-for-unit-tests-not-for-production-use
  access-token-validity-in-minutes: 30
  refresh-token-validity-in-days: 7

logging:
  level:
    com.salesflow.auth: DEBUG
    org.springframework.security: INFO 