spring:
  application:
    name: contact-core-service
  datasource:
    url: jdbc:postgresql://db.rdczmzmusjfemlynaqdf.supabase.co:5432/postgres?user=postgres&password=${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
    discovery:
      enabled: true
      service-id: ${spring.application.name}

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    org.springframework: INFO
    com.salesflow.contact: DEBUG
    org.hibernate.SQL: DEBUG

# Disable Eureka client
eureka:
  client:
    enabled: false

# Supabase Configuration
supabase:
  url: ${SUPABASE_URL}
  anon-key: ${SUPABASE_ANON_KEY}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY} 