spring:
  application:
    name: contact-core-service

  datasource:
    url: jdbc:postgresql://db.rdczmzmusjfemlynaqdf.supabase.co:5432/postgres
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        multitenancy: SCHEMA
        default_schema: contact

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: 
      - classpath:db/migration/public
      - classpath:db/migration/contact
      - classpath:db/migration/tenant/contact
    schemas: public,contact
    create-schemas: true
    validate-on-migrate: true
    out-of-order: true

  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
    discovery:
      enabled: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      validate-group-membership: false
      group:
        readiness:
          include: db

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
    disable-swagger-default-url: true

logging:
  level:
    org.springframework: INFO
    com.salesflow.contact: DEBUG
    com.salesflow.contact.config.tenant: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG

# Multi-tenancy configuration
multitenancy:
  entity:
    packages: com.salesflow.contact.domain
  namespace: contact_data
  schemas: contact,public
  migration:
    locations:
      public: classpath:db/migration/public
      contact: classpath:db/migration/contact
      tenant: classpath:db/migration/tenant/contact

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 10
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
