spring:
  application:
    name: contact-core-service
  datasource:
    # Replace with your Supabase connection URL
    # Format: jdbc:postgresql://<project-id>.supabase.co:5432/postgres
    url: ${SUPABASE_DB_URL}
    # Your Supabase database user (usually 'postgres')
    username: postgres
    # Replace with your Supabase database password
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  redis:
    host: localhost
    port: 6379
  cloud:
    config:
      enabled: false
      uri: http://localhost:8888
    discovery:
      enabled: true
      service-id: ${spring.application.name}

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    org.springframework: INFO
    com.salesflow.contact: DEBUG
    org.hibernate.SQL: DEBUG

# Disable Eureka client
eureka:
  client:
    enabled: false

# Supabase Configuration
supabase:
  url: ${SUPABASE_URL}
  anon-key: ${SUPABASE_ANON_KEY}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY} 