version: "3.8"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    hostname: auth-service
    ports:
      - "8081:8081"
    networks:
      - salesflow-network
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=0000
      - DB_NAME=postgres
      - JWT_SECRET_KEY=50e617183504456d656898939ecfa9eb5a1007518b9107c7f3c6126dbcf9d2c73c16c9dc92d6ff5a90c7853e8db38fe18d38accfbba7cff87dcfb195ee5850a2bb1a5067384cc053f5d3d10c5b41bb93b2d4acf08d3261b8ac9795300d05027fc773abd458415845e7bf72ba39291954ada18ed984218b20bd854601aa6bd975a20ad69e961f97cd32a12effb2cd094e59983cec46e2bacec7a2d9bfc9df988c7a039b6aacc2417bda0c88155bc94ea41bb48dd757ceade778ba705041c92c0349668d434e855667fcd5e037c89f10d14c9b997d2ee50841f4a8830e967e340f020ce75700ba5d15866d41024e2a133a9f04285ca17aaf0d6957a9356890595b
      - LOGGING_LEVEL_COM_SALESFLOW_AUTH=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=INFO
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - EUREKA_INSTANCE_HOSTNAME=auth-service
      - EUREKA_CLIENT_INITIALINSTANCEINFOREADYTIME=30
      - EUREKA_CLIENT_REGISTRYFETCHINTERVALSECONDS=5
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  postgres:
    image: postgres:17.5
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - salesflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  eureka-server:
    image: steeltoeoss/eureka-server:latest
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"
    networks:
      - salesflow-network
    environment:
      - EUREKA_CLIENT_REGISTERWITHEUREKA=false
      - EUREKA_CLIENT_FETCHREGISTRY=false
      - EUREKA_SERVER_ENABLESELFPRESERVATION=false
      - EUREKA_SERVER_WAITTIMEINSYNCWHENEMPTYMS=0
      - EUREKA_SERVER_RESPONSECACHEAUTOUPDATEINTERVALMS=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  salesflow-network:
    driver: bridge

volumes:
  postgres_data:
