version: "3.8"

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    hostname: auth-service
    ports:
      - "8081:8081"
    networks:
      - salesflow-network
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - LOGGING_LEVEL_COM_SALESFLOW_AUTH=${LOGGING_LEVEL_COM_SALESFLOW_AUTH}
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      - EUREKA_INSTANCE_PREFERIPADDRESS=${EUREKA_INSTANCE_PREFERIPADDRESS}
      - EUREKA_INSTANCE_HOSTNAME=${EUREKA_INSTANCE_HOSTNAME}
      - EUREKA_CLIENT_INITIALINSTANCEINFOREADYTIME=${EUREKA_CLIENT_INITIALINSTANCEINFOREADYTIME}
      - EUREKA_CLIENT_REGISTRYFETCHINTERVALSECONDS=${EUREKA_CLIENT_REGISTRYFETCHINTERVALSECONDS}
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  postgres:
    image: postgres:17.5
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - salesflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  eureka-server:
    image: steeltoeoss/eureka-server:latest
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"
    networks:
      - salesflow-network
    environment:
      - EUREKA_CLIENT_REGISTERWITHEUREKA=false
      - EUREKA_CLIENT_FETCHREGISTRY=false
      - EUREKA_SERVER_ENABLESELFPRESERVATION=false
      - EUREKA_SERVER_WAITTIMEINSYNCWHENEMPTYMS=0
      - EUREKA_SERVER_RESPONSECACHEAUTOUPDATEINTERVALMS=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

networks:
  salesflow-network:
    driver: bridge

volumes:
  postgres_data:
